# =============================================================================
# BuzzBase - Terraform Dockerfile
# =============================================================================

FROM hashicorp/terraform:1.6

# 追加ツールをインストール
RUN apk add --no-cache \
    bash \
    curl \
    jq

WORKDIR /terraform

ENTRYPOINT ["terraform"]
